- id: "getting-started"
  title: "Getting Started"
  icon: "icon-budicon-499"
  color: "orange"
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
  url: "/overview"
  articles:

    - title: "Applications"
      url: "/applications"

    - title: "Multifactor Authentication"
      url: "/mfa"
    
    - title: "Single Sign-On"
      url: "/sso/single-sign-on"

- id: "sdks"
  title: "SDKs"
  icon: "icon-budicon-342"
  color: "green"
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
  url: "/sdks"
  articles:

    - title: "Article 1"
      url: "/example/article1"

    - title: "Article 2"
      url: "/example/article2"
    
    - title: "Article 3"
      url: "/example/article3"

- id: "apis"
  title: "APIs"
  icon: "icon-budicon-546"
  color: "blue"
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
  url: "/api/info"
  articles:

    - title: "Article 1"
      url: "/example/article1"

    - title: "Article 2"
      url: "/example/article2"
    
    - title: "Article 3"
      url: "/example/article3"

- id: "appliance"
  title: "Appliance"
  icon: "icon-budicon-359"
  color: "pink"
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
  url: "/appliance"
  articles:

    - title: "Article 1"
      url: "/example/article1"

    - title: "Article 2"
      url: "/example/article2"
    
    - title: "Article 3"
      url: "/example/article3"

- id: "identity-glossary"
  title: "Identity Glossary"
  icon: "icon-budicon-715"
  color: "oil"
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
  url: "/identity"
  articles:

    - title: "Article 1"
      url: "/example/article1"

    - title: "Article 2"
      url: "/example/article2"
    
    - title: "Article 3"
      url: "/example/article3"

- id: "integrations"
  title: "Auth0 & Friends"
  icon: "icon-budicon-292"
  color: "blue-light"
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
  url: "/integrations"
  articles:

    - title: "Article 1"
      url: "/example/article1"

    - title: "Article 2"
      url: "/example/article2"
    
    - title: "Article 3"
      url: "/example/article3"
