- id: "getting-started"
  name: "Getting Started"
  icon: "icon-budicon-499"
  color: "orange"
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
  href: "/overview"
  articles:

    - name: "Applications"
      href: "/applications"

    - name: "Multifactor Authentication"
      href: "/mfa"
    
    - name: "Single Sign-On"
      href: "/sso/single-sign-on"

- id: "sdks"
  name: "SDKs"
  icon: "icon-budicon-342"
  color: "green"
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
  href: "/sdks"
  articles:

    - name: "Article 1"
      href: "/example/article1"

    - name: "Article 2"
      href: "/example/article2"
    
    - name: "Article 3"
      href: "/example/article3"

- id: "apis"
  name: "APIs"
  icon: "icon-budicon-546"
  color: "blue"
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
  href: "/api/info"
  articles:

    - name: "Article 1"
      href: "/example/article1"

    - name: "Article 2"
      href: "/example/article2"
    
    - name: "Article 3"
      href: "/example/article3"

- id: "appliance"
  name: "Appliance"
  icon: "icon-budicon-359"
  color: "pink"
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
  href: "/appliance"
  articles:

    - name: "Article 1"
      href: "/example/article1"

    - name: "Article 2"
      href: "/example/article2"
    
    - name: "Article 3"
      href: "/example/article3"

- id: "identity-glossary"
  name: "Identity Glossary"
  icon: "icon-budicon-715"
  color: "oil"
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
  href: "/identity"
  articles:

    - name: "Article 1"
      href: "/example/article1"

    - name: "Article 2"
      href: "/example/article2"
    
    - name: "Article 3"
      href: "/example/article3"

- id: "integrations"
  name: "Auth0 & Friends"
  icon: "icon-budicon-292"
  color: "blue-light"
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
  href: "/integrations"
  articles:

    - name: "Article 1"
      href: "/example/article1"

    - name: "Article 2"
      href: "/example/article2"
    
    - name: "Article 3"
      href: "/example/article3"
