- id: "articles"
  name: "Articles"
  href: "/overview"
  children:

    - name: "Applications"
      href: "/applications"
      icon: "icon-budicon-499"
      children:

        - name: "Overview"
          href: "/applications/overview"

        - name: "Advanced Configuration"
          href: "/applications/advanced-configuration"

        - name: "Addons"
          href: "/applications/addons" 

    - name: "Multifactor Authentication"
      href: "/mfa"
    
    - name: "Single Sign-On"
      href: "/sso/single-sign-on"

- id: "sdks"
  name: "SDKs"
  href: "/sdks"
  children:

    - name: "Article 1"
      href: "/example/article1"

    - name: "Article 2"
      href: "/example/article2"
    
    - name: "Article 3"
      href: "/example/article3"

- id: "apis"
  name: "APIs"
  href: "/api/info"
  children:

    - name: "Article 1"
      href: "/example/article1"

    - name: "Article 2"
      href: "/example/article2"
    
    - name: "Article 3"
      href: "/example/article3"

- id: "quickstarts"
  name: "QuickStarts"
  href: "/quickstarts"
  children:

    - name: "Article 1"
      href: "/example/article1"

    - name: "Article 2"
      href: "/example/article2"
    
    - name: "Article 3"
      href: "/example/article3"

- id: "appliance"
  name: "Appliance"
  href: "/appliance"
  children:

    - name: "Article 1"
      href: "/example/article1"

    - name: "Article 2"
      href: "/example/article2"
    
    - name: "Article 3"
      href: "/example/article3"
