## ------------------------------------------------------------
## Quickstart Configuration
## This document contains configuration for the quickstart
##
## ------------------------------------------------------------

appTypes:
  - title: Native App
    name: native
    description: "Mobile or Desktop, apps that runs natively in a device"
    example: "eg: iOS SDK"
    budicon: 243
    path: /articles/x-native-platforms

  - title: Web App
    name: web
    description: "A JavaScript front-end app that uses an API"
    example: "eg: AngularJS + NodeJS"
    budicon: 349
    path: /articles/x-web-platforms

  - title: Service
    name: service
    description: "Apps or Services running on your backend"
    example: "eg: Bash, Daemons"
    budicon: 649
    path: /articles/x-service-platforms
