articles:

  - title: Getting Started
    url: "#"
    icon: "icon-budicon-466"
    children:
      - title: Overview
        url: /overview
      - title: Developer Videos
        url: /videos
      - title: Architecture Scenarios
        url: /architecture-scenarios

  - title: "Applications"
    url: "/applications"
    icon: "icon-budicon-349"

  - title: "Rules"
    url: "/rules"
    icon: "icon-budicon-173"

  - title: "Identity Providers"
    url: "/identityproviders"
    icon: "icon-budicon-297"

  - title: "Single Sign-On"
    url: "/sso"
    icon: "icon-budicon-170"

  - title: "User Profile"
    url: "/user-profile"
    icon: "icon-budicon-289"

  - title: "Multifactor Authentication"
    url: "/multifactor-authentication"
    icon: "icon-budicon-243"
    children:

      - title: "Google Auth"
        url: "/multifactor-authentication/google-authenticator"
        children:

          - title: "Admin Guide"
            url: "/multifactor-authentication/google-auth/admin-guide"

          - title: "Dev Guide"
            url: "/multifactor-authentication/google-auth/dev-guide"

          - title: "User Guide"
            url: "/multifactor-authentication/google-auth/user-guide"

  - title: "Passwordless Authentication"
    url: "/connections/passwordless"
    icon: "icon-budicon-499"

  - title: "AD Connector"
    url: "/connector"
    icon: "icon-budicon-606"

apis:

  - title: "Overview"
    url: "/api/info"

  - title: "Testing with Postman"
    url: "/api/postman"

  - title: Authentication API
    url: "/api/authentication"

  - title: Management API
    url: "/api/management/v2/"
    children:
      - title: API Tokens
        url: /api/management/v2/tokens
      - title: Query String Syntax
        url: /api/management/v2/query-string-syntax
      - title: User Search
        url: /api/management/v2/user-search




appliance:

  - title: "Introduction"
    icon: "icon-budicon-714"
    url: "/appliance"

  - title: "Appliance Planning"
    icon: "icon-budicon-494"
    url: "/appliance/appliance-overview"
    children:
      - title: Geographic High-Availability
        url: /appliance/geo-ha
      - title: Deployment Modules
        url: /appliance/modules
      - title: Infrastructure Requirements
        url: /appliance/infrastructure
      - title: Customer Onboarding
        url: /onboarding/appliance-sprint
      - title: Onboarding Requirements
        url: /appliance/private-cloud-requirements

  - title: "Appliance Administration"
    icon: "icon-budicon-327"
    url: "#/admin"
    children:
      - title: Release Notes
        url: https://auth0.com/changelog/appliance
      - title: Administrator's Manual
        url: /appliance/admin
      - title: Dashboard/Configuration Area
        url: /appliance/dashboard
      - title: Monitoring Tools
        url: /appliance/monitoring
      - title: Command-Line Interface Tools
        url: /appliance/cli
      - title: Automatic Tenant Creation
        url: /appliance/admin/creating-tenants
      - title: Node Module Availibility
        url: /appliance/modules
      - title: Webtasks
        url: /appliance/webtasks
      - title: Disaster Recovery
        url: /appliance/geo-ha/disaster-recovery
